### ISSUE TITLE
ReferenceError: Set is not defined

### ISSUE THREAD

**Issue by tjmonsi** [gdgphilippines/devfest#88]
https://sentry.io/little-qairoes/devfest-ph-2017/issues/340326466/

```
ReferenceError: Set is not defined
  at None (../bower_components/custom-elements/src/Utilities.js:1:28)
  at None (webcomponents-hi-sd-ce-pf-index.js:1:1)
  at None (webcomponents-hi-sd-ce-pf-index.js:1:1)
```

**Comment by tjmonsi** [comment]
This is using Chromium 30. Might need to get an update on a possible use of a polyfill but this is low priority as of the moment
